export { default as homeIcon } from './homeIcon.vue'
export { default as exitIcon } from './exitIcon.vue'
export { default as togglerIcon } from './togglerIcon.vue'
export { default as starIcon } from './starIcon.vue'
export { default as forkIcon } from './forkIcon.vue'
